### ISSUE TITLE
Make sure the status change beep actually reflects the irc title

### ISSUE THREAD

**Issue by xSmurf** [FOULAB/foubot-modules#2]
A beep was added to the status change. the beep checks that the routine executes but it doesn't actually very that the title has been changed. It should only play on actual confirmation.

**Comment by sfxman** [comment]
Also I suggest it make a sad trombone noise upon failure.

**Comment by Danukeru** [comment]
Dev has moved over to foubot2 in golang. Should have this behaviour now.
